# --- KYVE-DLT CONFIGURATION
# Supported: info (default), debug, none
log_level: "info"

# --- SOURCE CONFIGURATION ---
# A source is a KYVE pool including the validated data that will be loaded into the destination.
sources:
  - name: osmosis
    pool_id: 1
    step_size: 20
    endpoint: "https://api.kyve.network"
    # Column schema: base (default), tendermint, tendermint_preprocessed
    schema: "tendermint_preprocessed"
  - name: archway
    pool_id: 2
    step_size: 20
    endpoint: "https://api.kyve.network"
    # Column schema: base (default), tendermint, tendermint_preprocessed
    schema: "tendermint"
  - name: axelar
    pool_id: 3
    step_size: 20
    endpoint: "https://api.kyve.network"
    # Column schema: base (default), tendermint, tendermint_preprocessed
    schema: "tendermint"
  - name: cronos
    pool_id: 5
    step_size: 20
    endpoint: "https://api.kyve.network"
    # Column schema: base (default), tendermint, tendermint_preprocessed
    schema: "tendermint"
  - name: noble
    pool_id: 7
    step_size: 20
    endpoint: "https://api.kyve.network"
    # Column schema: base (default), tendermint, tendermint_preprocessed
    schema: "tendermint"
  - name: celestia
    pool_id: 9
    step_size: 20
    endpoint: "https://api.kyve.network"
    # Column schema: base (default), tendermint, tendermint_preprocessed
    schema: "tendermint"

# --- DESTINATION CONFIGURATION ---
# Supported destinations types: big_query, postgres
# (Only specify values of the selected type.)
destinations:
  - name: big_query_example
    type: "big_query"
    project_id: ""
    dataset_id: ""
    table_id: ""
    worker_count: 2
    bucket_worker_count: 2
  - name: postgres_example
    type: "postgres"
    connection_url: ""
    table_name: ""
    worker_count: 4

# --- CONNECTION CONFIGURATION ---
# Connections are mappings of source and destination.
# A connection is required for all sync processes.
connections:
  - name: connection_example
    source: osmosis
    destination: big_query_example

# --- LOADER CONFIGURATION ---
loader:
  channel_size: 8
  csv_worker_count: 4