# --- KYVE-DLT CONFIGURATION
# Supported: info (default), debug, none
log_level: "info"

# --- SOURCE CONFIGURATION ---
# A source is a KYVE pool including the validated data that will be loaded into the destination.
# Supported pool runtimes: @kyvejs/tendermint
source:
  pool_id: 0
  step_size: 1
  endpoint: "https://api.kyve.network"
  # Column schema: base (default), tendermint_preprocessed
  schema: "base"

  # ---! Only set these values when you want to load a specific range of bundles. !---
  # ID of the first bundle that will be loaded into the destination.
  # Default: 0 (first bundle of the pool)
  # from_bundle_id: 0 # <-- Remove this comment if you want to set a specific start bundle
  # ID of the last bundle that will be loaded into the destination.
  # Default: 9223372036854775807 (process runs until all bundles are loaded)
  # to_bundle_id: 100 # <-- Remove this comment if you want to set a specific end bundle

# --- DESTINATION CONFIGURATION ---
# Supported destinations: BigQuery, Postgres
# (Only specify values of the selected type.)
destination:
  # Destination type: big_query (default), postgres
  type: "big_query"

  # BigQuery config
  big_query:
    project_id: ""
    dataset_id: ""
    table_id: ""
    big_query_worker_count: 1
    bucket_worker_count: 1

  # Postgres config
  postgres:
    connection_url: ""
    table_name: ""
    worker_count: 2

# --- LOADER CONFIGURATION ---
loader:
  channel_size: 8
  csv_worker_count: 4